language: scala

scala:
   - 2.12.4
   
jdk:
   - oraclejdk8
   - openjdk8
   
script:
   - sbt ++$TRAVIS_SCALA_VERSION ";test ;hepekTestsProject/hepek ;hepekTestsProject/test"

cache:
  directories:
    - $HOME/.ivy2
    
notifications:
  email:
    - sakib@sake.ba






